### ISSUE TITLE
Allow work with nonTask code

### ISSUE THREAD

**Issue by Lonli-Lokli** [AscentSoftware/tap-ts#3]
Currently it's required to have Task-related return, eg

```
 const probe = (n: number): T.Task<void> => {
    probes.push(n);
    return T.of(undefined);
  };

const runTask = pipe(
    start(0),
    tap(probe),
    chain(() => TE.right(100)),
  );
```

while it will be much less code with this
```
const runTask = pipe(
    start(0),
    tap(n =>  probes.push(n)),
    chain(() => TE.right(100)),
  );
```

**Comment by mstn** [comment]
Hi @Lonli-Lokli, it makes sense. Thanks for the suggestion.

Feel free to open a PR. However, I should say that, unfortunately, this lib is not under active development.
